### ISSUE TITLE
Dinamik vaxtın təyin edilməsi

### ISSUE THREAD

**Issue by seyidkanan** [sarkhanrasullu/periodic_thread_scheduler#1]
Bu təqdim edilən nümunə ilə dinamik vaxtı təyin eləmək olar?

**Comment by sarkhanrasullu** [comment]
Sualı dəqiqləşdirin zəhmət olmasa. Bu app Threadin verilən gün, saat və dəqiqədə işi görməyini təmin edir. Normalda thread scheduler sadəcə məsələn 1 saatdan sonra işə düşməyini təmin edir. Lakin siz məhz filan gün, filan saatda işə düşməsini təmin edə bilmirsiniz. Bu app həmin problemi aradan qaldırır.

**Comment by seyidkanan** [comment]
Yəni məsələn mənə nə vaxt email göndərmək lazım olan vaxtlar gələcək və mən vaxtları proqramda təyin edəcəm. Belə bir case.

**Comment by sarkhanrasullu** [comment]
SchedularUtil.schedule(ScheduledExecutorService executorService, int hour, int minute, int second, int delayDay, Runnable r)

SchedularUtil.schedule(int hour, int minute, int second, int delayDay, Runnable r)

method əlavə etdim.  İstədiyiniz threadi bu methoda göndərərək xüsusi zaman üçün schedule edə bilərsiniz.
